[{u'category': 5,
  u'category_name': u'Barrier Free (limited mobility)',
  u'id': 31,
  u'name': u'Accessible Trail'},
 {u'category': 5,
  u'category_name': u'Barrier Free (limited mobility)',
  u'id': 6,
  u'name': u'Accessible Restrooms'},
 {u'category': 4, u'category_name': u'Surface', u'id': 30, u'name': u'Paved'},
 {u'category': 4, u'category_name': u'Surface', u'id': 28, u'name': u'Dirt'},
 {u'category': 3,
  u'category_name': u'Activities',
  u'id': 17,
  u'name': u'Birding'},
 {u'category': 10,
  u'category_name': u'Regional Trail',
  u'id': 33,
  u'name': u'San Francisco Bay Trail'},
 {u'category': 5,
  u'category_name': u'Barrier Free (limited mobility)',
  u'id': 27,
  u'name': u'Accessible Picnic Area'},
 {u'category': 2,
  u'category_name': u'Amenities',
  u'id': 18,
  u'name': u'Primary Park Entrance'},
 {u'category': 2,
  u'category_name': u'Amenities',
  u'id': 2,
  u'name': u'Restrooms'},
 {u'category': 2,
  u'category_name': u'Amenities',
  u'id': 4,
  u'name': u'Parking'},
 {u'category': 2,
  u'category_name': u'Amenities',
  u'id': 22,
  u'name': u'Picnic Tables'},
 {u'category': 3,
  u'category_name': u'Activities',
  u'id': 11,
  u'name': u'Hiking'}]
